batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405191314
train_epochs: 1000
train_workers: 20
vocab: B?'XudQ#VhjgC7"f KZ!/Y*60k,)4TE&IyoLn2e(a3:1PNqlz-W.OMSiHsw;RU5Dm9GAF+r8xcpvtbJ
width: 1408
