batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405182035
train_epochs: 1000
train_workers: 20
vocab: CDUZ5Odaf "q'isFtn47MzK;6L1m9:)lcj?Y3W0bh#ReN.gTXr!wJ(+vuE/G*k2,Vpy&xoP8IHQA-SB
width: 1408
