batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405191310
train_epochs: 1000
train_workers: 20
vocab: 6!+AYdGn)3TQl7HJ8,MKR'-CFsg Sf#OW.5i?:LmX0q*Zv1uNjbPwyop9Dr(eUEt4a2Ic"/xh;B&kzV
width: 1408
