batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405191339
train_epochs: 1000
train_workers: 20
vocab: 2TmtDe,1G*r#5n!/i.Xag6xw'IWPA4":(vMO-QkVHB8Y0oJFNCu; RpE&Zz+Uyl3hb9LqscKj?S7d)f
width: 1408
