batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405221201
train_epochs: 1
train_workers: 20
vocab: F2tj+wB O1s7Ie:!H'lU.nGkQdx/oMN8c"4(YA6;EzqTCLXWf9u?KpaS-PmyrZ*h3gi)5b0&J#VvRD,
width: 1408
