batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405182024
train_epochs: 1000
train_workers: 20
vocab: /CDjbf0.JyATPR*kQ?pre#zWH2u(aF;Gd5-XYcK6'Sx)q EU"3VNZsmh:I7,w+og&vi9nl!8tLMO41B
width: 1408
