batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405182028
train_epochs: 1000
train_workers: 20
vocab: uwai3/AI*XH5JxnQet 1NhYRC2kPoS!-gmdF0:6GTl'j7syK,98rfEZOLB?+.VU;)v"qpMb4Wc&#(Dz
width: 1408
