batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405191345
train_epochs: 1000
train_workers: 20
vocab: QYEFjA"Pekvc8;w.r!?0d4oTU/t,:JyNXSMxg1Lfb V+HD7*2s&KRmulCapB#5IGqzZi-3hWO'6(n9)
width: 1408
