batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405191312
train_epochs: 1000
train_workers: 20
vocab: a*w#0F2dxvYO'Azl:IfHNk4()go81DQmcntpVGjS9yBC,.u!MsZ "RX+LiqTK3e&-bPW7EUh5;J/r?6
width: 1408
