batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405191338
train_epochs: 1000
train_workers: 20
vocab: gE9Kb,4fd)ZHBhSk:*iL/MyAX0DoIsPUG'&lQqt#z6njN?rvupYcwOVJ7W1x (82TC.emR3a+;!-5"F
width: 1408
