batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202405221014
train_epochs: 1
train_workers: 20
vocab: gujN*M#,B9hYSo)rIO'dDAEHlit 2.cJX4:/a(!LKz;PCRnUqmF1b8Z0xyTkw?+5eVQfW6"p-7v&sG3
width: 1408
